### ISSUE TITLE
Scrape the existing members list

### ISSUE THREAD

**Issue by emmyft** [osc-delft/temp-issues#5]
After talking to Comms - it doesn't seem easy to get the info off the existing website. I'm up to scrapping it (also just for fun (; )
- [ ] Scrape the existing members list
- [ ] Re-format info and add to _data/people.yaml
- [ ] Check with DS to keep the members' list up-to-date

**Comment by Metahofzicht** [comment]
Hoi Emmy,

I already assembled all the names from the site (I thought I send you the file) Right now, I cannot search for the file, but let me look for it, before you start to redo what I already did ☺

Groet, Meta
